In [1]:
import numpy as np

# numpy is used for
1. high performance calculation on vectors and matrices -- uses C as its lower level engine
   (BLAS/LAPACK)
2. do complex calculations

In [ ]:
# numpy --> random --> random/randn/rand/randint
#       --> cosine
#       --> mean

In [2]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)

In [4]:
type(my_list), type(arr)

(list, numpy.ndarray)

In [6]:
np.zeros((4,4)), np.ones((4,4))

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [8]:
np.random.random((4,4))
# the uniformed distrubuted randomization between [0, 1)

array([[0.1496053 , 0.27401047, 0.04313724, 0.51859105],
       [0.5838184 , 0.04834057, 0.16464156, 0.23418057],
       [0.93248137, 0.02741065, 0.79325845, 0.98970038],
       [0.63405269, 0.65048656, 0.90175079, 0.70661673]])

In [10]:
np.random.randn(4,4)
# the gaussian distribution with mean = 0 and sigma = 1

array([[ 1.31556355,  0.2068434 ,  1.5536713 ,  0.55477809],
       [ 0.40065446, -1.50227042,  0.24814107, -0.49305877],
       [-0.63908637,  0.92613456, -0.15137067, -1.99342782],
       [-1.55948399,  0.03820832,  1.30057114,  0.54384403]])

In [14]:
np.random.randint(-100,100,(4,4))

array([[ 62,  88,  -3,  87],
       [ 40, -28, -87,   9],
       [-51, -59, -32,  47],
       [ 52,  57,  36, -18]])

In [34]:
n = 10000
a = np.random.randn(n)
import time

In [47]:
c = time.time()
results = np.zeros(n)
for i in range(n):
    results[i] = np.exp(a[i])
print("Execution took {} ms.".format((time.time()-c)*1000))

Execution took 14.883041381835938 ms.


In [48]:
c = time.time()
np.array(list(map(np.exp, a)))
print("Execution took {} ms.".format((time.time()-c)*1000))

Execution took 11.491775512695312 ms.


In [49]:
c = time.time()
np.exp(a)
print("Execution took {} ms.".format((time.time()-c)*1000))

Execution took 0.09918212890625 ms.


In [51]:
a.dtype

dtype('float64')

In [55]:
a = np.random.random((10,5))
b = np.random.random((10,5))
c = np.random.random((5,20))

In [56]:
a * b # element-wise + - * /

array([[0.71110356, 0.49826667, 0.61995325, 0.0837724 , 0.05857412],
       [0.00809404, 0.20405804, 0.19184927, 0.31417188, 0.51399305],
       [0.33216023, 0.52299293, 0.06302248, 0.55213759, 0.06687733],
       [0.04111154, 0.13682544, 0.59338123, 0.60538995, 0.06367105],
       [0.14158113, 0.38889696, 0.28555164, 0.35852062, 0.13723449],
       [0.31640354, 0.11177095, 0.02291502, 0.02237482, 0.05019748],
       [0.09761265, 0.68934887, 0.02154793, 0.01331432, 0.02464083],
       [0.45568149, 0.05389595, 0.1144853 , 0.12995146, 0.03348017],
       [0.00862374, 0.16151453, 0.46071521, 0.28174773, 0.29219589],
       [0.50197551, 0.32784605, 0.24980071, 0.16511517, 0.09566533]])

In [59]:
np.matmul(a,c).shape

(10, 20)

In [61]:
(a @ c).shape

(10, 20)

In [64]:
np.allclose(np.matmul(a,c),(a@c))

True